name: run-tests

on:
    push:
    pull_request:
    schedule:
        - cron: '0 0 * * *'

jobs:
    run-tests:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: [8.3, 8.2, 8.1, 8.0]
                laravel: [11.*, 10.*, 9.*]
                dependency-version: [prefer-lowest, prefer-stable]
                exclude:
                    -   php: 8.2
                        laravel: 9.*
                        dependency-version: prefer-lowest
                    -   php: 8.1
                        laravel: 11.*
                    -   php: 8.0
                        laravel: 11.*
                    -   php: 8.0
                        laravel: 10.*


        name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }} - ${{ matrix.dependency-version }}

        steps:
            - name: Update apt
              run: sudo apt-get update --fix-missing

            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: xdebug

            - name: Get Composer cache cirectory
              id: composer-cache
              run: |
                echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache Composer packages
              uses: actions/cache@v3
              with:
                path: ${{ steps.composer-cache.outputs.dir }}
                key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                restore-keys: |
                  ${{ runner.os }}-composer-

            - name: Install dependencies
              run: |
                  composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
                  composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

            - name: Execute tests
              run: vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
